name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Add version information to jinja2 files
      run: "sed -i 's/Version: dev/Version: ${{ github.ref_name }}/' src/*.jinja2"

    - name: Add version information to python file
      run: sed -i "s/^VERSION =.*/VERSION = '${{ github.ref_name }}'/" src/main.py

    - name: Build docker image
      run: docker build . --tag bessarabov/visualize_advent_of_code_private_leaderboard:${{ github.ref_name }}

    - name: Push docker image
      run: docker push bessarabov/visualize_advent_of_code_private_leaderboard:${{ github.ref_name }}
